spring:
  profiles:
    active: dev

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8000
  servlet:
    context-path: /titanic

mybatis:
  type-aliases-package: com.landingguy.Titanic.entity
  mapper-locations: classpath:mybatis/*Mapper.xml
